server:
  port: 6001


mybatis:
  basepackage: com.github.wxiaoqi.cloud.sample.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
  enabled: true
  base-package: com.codedog.gitstar
  title: gitstar
  version: 1.0.0.SNAPSHOT
  description: gitstar项目
  contact:
    name: codedog


spring:
  application:
    name: gitstar
  datasource:
    name: 管理后端数据库
    url: jdbc:mysql://www.orzjj.com:6804/cloud_admin_v1?useUnicode=true&characterEncoding=UTF8
    username: cloud
    password: cloud@abc
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 2
    host: c2.orzjj.com
    port: 7235
    jedis:
      pool:
          max-active: 20
  sleuth:
    enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: c2.orzjj.com:8848
    sentinel:
      transport:
        dashboard: c2.orzjj.com:8080


auth:
  serviceId: ace-admin
  user:
    token-header: Authorization
  client:
    id: gitstar  #不填则默认读取spring.application.name
    secret: gitstar^20201222

logging:
  level:
    com.github.wxiaoqi.security.sample: info
    com.codedog.gitstar: info
#    com
#    org.springframework: DEBUG
    org.springframework: warn


management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: false

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ## 并发执行的最大线程数，默认10
      maxQueueSize: 1000 ## BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ## 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000